In [2]:
import pandas as pd

In [29]:
data = pd.read_csv("globalAirQuality.csv")

# selection
data.head(10) # top 10 rows print


# --------------------------- COLUMNS BASED ACCESS --------------------------------
# specific column based access 
data[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [30]:
# ----------------------------------- ROW SELECTION --------------------------------
# loc (labelled based access) vs iloc (index based access)
data.loc[0]
data.loc[0:5] # start: END inclusive

data.iloc[0]
data.iloc[0:5] # end exclusive

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [31]:
# selecting cells using iloc vs loc

data.loc[0:5 , "city"] # range , column label name
data.loc[0:5 , ["country" , "city" , "aqi"]]


# using iloc
# data.iloc[0:5 , "city"] ------------> ERROR

# data.columns ----------> to print column index
data.columns
data.iloc[0:5 , [1,2,11]] # range of rows , column index

  country      city  aqi
0      US  New York  108
1      US  New York   90
2      US  New York   84
3      US  New York  158
4      US  New York   97

In [32]:
#  access cell using at and iat

# using at (for labelled)
data.at[0,"city"]

# using iat (for index)
data.iat[0,1]


# NOTE: ALWAYS KEEP COPY OF ORG DATA BEFORE CHANGE IT> >copy() FUNCTION

'US'

In [44]:
# filtering DATA 

# use list of list
data[ data["aqi"] > 100]

data[ (data["aqi"] > 100) & (data["temperature"] > 35)]

# display desired column
data[(data["aqi"] > 100) & (data["temperature"] > 35)][["city","country"]]

           city country
6      New York      US
7      New York      US
17     New York      US
82     New York      US
105    New York      US
...         ...     ...
17866    Zurich      CH
17874    Zurich      CH
17883    Zurich      CH
17902    Zurich      CH
17950    Zurich      CH

[909 rows x 2 columns]

In [49]:
# QUERY FILTER (best method)

data.query("aqi > 150 & temperature > 35")[["city" , "country"]]

aqi_good = 30
# print best city to live
data.query("aqi < @aqi_good")[["city" , "country" , "aqi"]]

                city country  aqi
533      Los Angeles      US   27
892           London      GB   29
960           London      GB   16
6115          Riyadh      SA   29
9914        Shanghai      CN   27
10715      Singapore      SG   29
10997        Bangkok      TH   27
15279  San Francisco      US   26